import Head from "next/head";
import React from "react";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import styles from "../styles/Home.module.css";

export default function Home() {
  const { data: session, loading } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
            Not signed In <br />
            <button onClick={signIn}>Sign In</button>
          </>
        )}

        {session && (
          <>
            Signed In as {session.user.email} <br />
            <div>You can now access our super secret pages</div>
            <button onClick={signOut}>Sign Out</button>
          </>
        )}
      </main>
    </div>
  );
}
